#!/bin/sh
while true; do

	# Clean up previously running apps, gracefully at first then harshly
	killall -TERM chromium-browser 2>/dev/null;
	killall -TERM matchbox-window-manager 2>/dev/null;
	sleep 2;
	killall -9 chromium-browser 2>/dev/null;
	killall -9 matchbox-window-manager 2>/dev/null;

	rm -rf ~/.cache;
	rm -rf ~/.config;
	rm -rf ~/.pki;
	mkdir -p ~/.config/chromium/Default
	sqlite3 /home/pi/.config/chromium/Default/Web\ Data "CREATE TABLE meta(key LONGVARCHAR NOT NULL UNIQUE PRIMARY KEY, value LONGVARCHAR); INSERT INTO meta VALUES('version','56'); CREATE TABLE keywords (foo INTEGER);";

	xres=$( cat /sys/module/*fb*/parameters/fbwidth )
	yres=$( cat /sys/module/*fb*/parameters/fbheight )

	echo "Detected screen resolution $xres x $yres -- changing chrome preferences to use this"

	sed -e "s#//.\+\$##g" /boot/chromium-Preferences | sed -e "s/\"right\": [0-9]\+/\"right\": $xres/" | sed -e "s/\"bottom\": [0-9]\+/\"bottom\": $yres/" > ~/.config/chromium/Default/Preferences

	xset s off
	xset -dpms
	matchbox-window-manager -use_cursor no -use_titlebar no &

	chromium-browser --start-maximized --kiosk `cat /boot/starturl.txt`
done;

